### ISSUE TITLE
ERROR [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)

### ISSUE THREAD

**Issue by 741215208** [codebox/https-certificate-expiry-checker#1]
info
 python3.7 check-certificates.py d.10jqka.com.cn
d.10jqka.com.cn ERROR [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)

**Comment by codebox** [comment]
I tried the same command and got a successful response:

> python check-certificates.py d.10jqka.com.cn
Checking 1 endpoint...
d.10jqka.com.cn OK    expires in 290 days

If you Google around there are a number of reasons for this error, mostly relating to your local certificates. Without knowing more about your local setup there isn't much more I can say.
